### ISSUE TITLE
Send reindekseringsspørringer direkte til pod'en

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-fulltext-search-rabbit-consumer#9]
Nå sendes spørringer gjennom ingressen, som gir 502 etter 30sek. Send spørringene direkte til pod'en for å kunne avvente til fulltext faktisk blir ferdig med reindekseringer

**Comment by valosnah** [comment]
Fikset vha konfigurasjonsendring i helm-template

**Comment by valosnah** [comment]
Før:
![image](https://user-images.githubusercontent.com/8625716/127481160-b7e1a0f5-1d9b-4774-8884-8c6631ab8606.png)

Etter:
![image](https://user-images.githubusercontent.com/8625716/127481194-0cd358e2-5fa4-4a99-b79c-7a1b9ee793a5.png)

**Comment by shenluna** [comment]
Verifisert OK
